#!/bin/zsh
# File              : prompt_eucalyptus_setup
# Author            : Hiroki Konishi <relastle@gmail.com>
# Date              : 10.06.2019
# Last Modified Date: 10.06.2019
# Last Modified By  : Hiroki Konishi <relastle@gmail.com>

# prompt_eucalyptus_setup
# Copyright (c) 2019 Hiroki Konishi <relastle@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

POWERLINE_SEPARATOR=''
NERD_FONT_GIT=''
NERD_FONT_HOME=''
NERD_FONT_DOCKER=''

TEXT_COLOR_WHITE="white"
TEXT_COLOR_BLACK="black"

POWERLINE_A_COLOR="cyan"
POWERLINE_B_COLOR="green"
POWERLINE_C_COLOR="blue"

vi_status='INSERT'
VI_INSERT_COLOR='yello'
VI_NORMAL_COLOR='cyan'
vi_status_color="${VI_INSERT_COLOR}"

chpwd_flag=false

# set STATUS_COLOR: cyan for "insert", green for "normal" mode.
prompt_eucalyptus_vim_mode() {
	vi_status="${${KEYMAP/vicmd/NORMAL}/(main|viins)/INSERT}"
	vi_status_color="${${KEYMAP/vicmd/${VI_NORMAL_COLOR}}/(main|viins)/${VI_INSERT_COLOR}}"
    zle reset-prompt
}

prompt_eucalyptus_precmd () {
    # echo "chpwd_flag = ${chpwd_flag} @ precmd"
    if [[ $chpwd_flag != true ]] then
        vcs_info #&& echo "get VCS_INFO precmd"
    fi
    chpwd_flag=false
}

prompt_eucalyptus_preexec () {
    chpwd_flag=false
}

prompt_eucalyptus_chpwd () {
    vcs_info #&& echo "get VCS_INFO chpwd"
    chpwd_flag=true
}

prompt_eucalyptus_render() {
    if [ -z "$DOCKER_CONTAINER" ]
    then
        POWERLINE_LEFT_A=""
    else
        POWERLINE_LEFT_A="%K{${POWERLINE_A_COLOR}}%F{${TEXT_COLOR_BLACK}} "$NERD_FONT_DOCKER" "$DOCKER_CONTAINER" %k%f%K{${POWERLINE_B_COLOR}}%F{${POWERLINE_A_COLOR}}"$POWERLINE_SEPARATOR
    fi

    POWERLINE_LEFT_B="%K{${POWERLINE_B_COLOR}}%F{${TEXT_COLOR_BLACK}} "$NERD_FONT_HOME" %c %k%f%K{${POWERLINE_C_COLOR}}%F{${POWERLINE_B_COLOR}}"$POWERLINE_SEPARATOR
    POWERLINE_LEFT_C="%k%f%K{${POWERLINE_C_COLOR}}%F{${TEXT_COLOR_WHITE}} $NERD_FONT_GIT "'${vcs_info_msg_0_}'" %k%f%{${reset_color}%}%F{${POWERLINE_C_COLOR}}$POWERLINE_SEPARATOR%{${reset_color}%}"

    RPROMPT="%F{"'${vi_status_color}'"}[--"'${vi_status}'"--] %F{green}%~%f"
    PROMPT="${POWERLINE_LEFT_A}${POWERLINE_LEFT_B}${POWERLINE_LEFT_C} "
}

prompt_eucalyptus_setup() {
    export KEYTIMEOUT=20

    fmt_staged="%F{red} %f"
    fmt_unstaged="%F{yellow} %f"
    fmt_branch="%F{${TEXT_COLOR_WHITE}}%b%f%u%c%f"
    fmt_action="%F{red}[%a]%f"

	add-zsh-hook precmd prompt_eucalyptus_precmd
	add-zsh-hook preexec prompt_eucalyptus_preexec
	add-zsh-hook chpwd prompt_eucalyptus_chpwd

	zle -N zle-line-init prompt_eucalyptus_vim_mode
	zle -N zle-keymap-select prompt_eucalyptus_vim_mode

    autoload -Uz vcs_info
    zstyle ":vcs_info:*" enable git
    zstyle ':vcs_info:git:*' check-for-changes true
    zstyle ':vcs_info:git:*' stagedstr "${fmt_staged}"
    zstyle ':vcs_info:git:*' unstagedstr "${fmt_unstaged}"
    zstyle ':vcs_info:*' formats "${fmt_branch}"
    zstyle ':vcs_info:*' actionformats "${fmt_branch}${fmt_action}"

    prompt_eucalyptus_render
}

prompt_eucalyptus_setup
